spring.application.name=springbootdemo

spring.datasource.url=jdbc:postgresql://localhost:5432/springdemo
spring.datasource.username=postgres
spring.datasource.password=1136

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true